CREATE TABLE IF NOT EXISTS News (
    Id SERIAL PRIMARY KEY NOT NULL,
    title TEXT NOT NULL,
    content TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS Newscategories (
    categoryId BIGINT NOT NULL PRIMARY KEY,
    newsId BIGINT NOT NULL REFERENCES News(Id)
);